#define BOM "bom"
#define BOMVERSION "version"
#define FileVersion	"2.0.4"
#define ATTRIBUTES "attributes"
#define INSTANCES "instances"
#define TOPID "topId"
#define MODELS "models"
#define MESH "mesh"
#define LOD1 "lod1"
#define ACCESOR "accesor"
#define FILENAME "filename"
#define OFFSET "offset"
#define LENGTH "length"
#define MATERIALS "materials"
#define TYPE "type"
#define  TRANSPARENCY "transparency"
#define  DIFFUSECOLOR "diffuseColor"
#define  AMBIENTCOLOR "ambientColor"
#define  DIFFUSETEXTURE "diffuseTexture"
#define  SPECULARTEXTURE "specularTexture"
#define REF "ref"
#define IMAGES "images"
#define URI "uri"
#define  REFLECTIVETEXTURE "reflectiveTexture"

//金正金扩展
#define NAME "name"
#define MIXINGFACTOR "mixingFactor"
#define FRONTTEXTURE "frontTexture"
#define BACKTEXTURE	"backTexture"

#define INDEX_INSTANCEID   0
#define INDEX_PLCID			   1
#define INDEX_MODELID        2
#define INDEX_VISIBLE			   3
#define INDEX_MATRIX		   4
#define INDEX_INSCHILDREN 5
#define INDEX_MATERIAL		6
#define INDEX_PARENTID		7

#define  MESH_TYPE                      L"type"
#define	 MESH_NORMAL                    L"normal"
#define  MESH_ORIGIN                    L"origin"
#define  MESH_AXISORIGIN                L"axisOrigin"
#define  MESH_AXISDIRECTION             L"axisDirection"
#define  MESH_RADIUS                    L"radius"
#define  MESH_ORIGINRADIUS              L"originRadius"
#define  MESH_MINORRADIUS               L"minorRadius"
#define  MESH_MAJORRADIUS               L"majorRadius"
#define  MESH_CENTEREPOINT              L"centerPoint"
#define  MESH_DIRECTION                 L"direction"
#define  MESH_STARTPOINT                L"startPoint"
#define  MESH_ENDPOINT                  L"endPoint"
#define  MESH_LENGTH                    L"length"
#define  MESH_XDIRECTION                L"xDirection"
#define  MESH_YDIRECTION                L"yDirection"
#define  MESH_ZDIRECTION                L"zDirection"