/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_svllib_SVLLibTest */

#ifndef _Included_com_example_svllib_SVLLibTest
#define _Included_com_example_svllib_SVLLibTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_svllib_SVLLibTest
 * Method:    Test
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_svllib_SVLLibTest_Test
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
