#pragma once


#ifdef _LANGUAGE_EN_
#define IDS_STRING_ANIMATIONG_SOUND_FAILURE "Sound(%s)play failure!"
#define IDS_STRING_TARGETOBJECTTYPE_NAME_INS "Model"
#define IDS_STRING_TARGETOBJECTTYPE_NAME_PMI "PMI"
#define IDS_STRING_TARGETOBJECTTYPE_NAME_CAM "Camera"
#define IDS_STRING_TARGETOBJECTTYPE_NAME_CLIP "Clip plane"
#define IDS_STRING_TARGETOBJECTTYPE_NAME_SOUND "Sound"
#define IDS_STRING_TARGETOBJECTTYPE_NAME_IMAGE "Image"
#define IDS_STRING_TARGETOBJECTTYPE_NAME_ZOOM "Section zoom out"
#define IDS_STRING_POSITON      "Position"
#define IDS_STRING_SHOW_HIDE    "ShowHide"
#define IDS_STRING_COLOR        "Color"
#define IDS_STRING_CAMERA       "Camera"
#define IDS_STRING_SECTION      "Section"
#define IDS_STRING_CLIP_SECTION "CLIP:Section"
#define IDS_STRING_NEW_GROUP    "New group"
#define IDS_STRING_STEP         "Step "
#define IDS_STRING_PROCESS      "Process "
#define IDS_STRING_ANIMATION_MANAGER "Animation process manager"
#define IDS_STRING_GROUP        "Group%d"
#define IDS_STRING_NO_PROCESS      "Please create a step first."
#else
#define IDS_STRING_ANIMATIONG_SOUND_FAILURE "声音(%s)播放失败!"
#define IDS_STRING_TARGETOBJECTTYPE_NAME_INS "模型"
#define IDS_STRING_TARGETOBJECTTYPE_NAME_PMI "PMI"
#define IDS_STRING_TARGETOBJECTTYPE_NAME_CAM "摄像机"
#define IDS_STRING_TARGETOBJECTTYPE_NAME_CLIP "剖面"
#define IDS_STRING_TARGETOBJECTTYPE_NAME_SOUND "声音"
#define IDS_STRING_TARGETOBJECTTYPE_NAME_IMAGE "图片"
#define IDS_STRING_TARGETOBJECTTYPE_NAME_ZOOM "局部放大"
#define IDS_STRING_POSITON      "位置"
#define IDS_STRING_SHOW_HIDE    "显隐"
#define IDS_STRING_COLOR        "颜色"
#define IDS_STRING_CAMERA       "摄像机"
#define IDS_STRING_SECTION      "剖面"
#define IDS_STRING_CLIP_SECTION "截面"
#define IDS_STRING_NEW_GROUP    "新建分组"
#define IDS_STRING_STEP         "步骤"
#define IDS_STRING_PROCESS      "过程"
#define IDS_STRING_ANIMATION_MANAGER "动画过程管理器"
#define IDS_STRING_GROUP        "组%d"
#define IDS_STRING_NO_PROCESS      "没有找到动画步骤，请先创建！"
#endif
